# Reference this view as customer_success__product
schema: CUSTOMER_SUCCESS
table_name: PRODUCT

dimensions:
  id:
    sql: '"ID"'
    format: ID
    primary_key: true

  created_date:
    sql: '"CREATED_DATE"'

  name:
    sql: '"NAME"'

  family:
    sql: '"FAMILY"'

measures:
  count:
    aggregate_type: count
